---
app:
  name: "gomongo"
  version: "0.0.2"
  port: 8080
database:
  host: "0.0.0.0"
  port: 27017
  username: "mongoadmin"
  password: "c2VjcmV0"
  database: "admin"
  uri: ""
  collection:
    collection: "book"
    database: "admin"
  type: "mongodb"