apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: psql-1
  namespace: psql-1
spec:
  serviceAccountName: psql-install
  packageRef:
    refName: psql.azure.references.services.apps.tanzu.vmware.com
    versionSelection:
      constraints: 0.0.1-alpha
  values:
  - secretRef:
      name: psql-1-values
---
apiVersion: v1
kind: Secret
metadata:
  name:  psql-1-values
  namespace: psql-1  
stringData:
  values.yml: |
    name: psql-1
    namespace: psql-1
    create_namespace: false
    aso_controller_namespace: azureserviceoperator-system
    resource_group:
      name: psql-1
      use_existing_resource_group: false
    server:
      version: "13"
      administrator_name: trpadmin
      instance_type: Standard_D4s_v3
      instance_tier: GeneralPurpose
      instance_storage_size_gb: 128
    database:
      name: testdb
    firewall_rules:
      - startIpAddress: 0.0.0.0
        endIpAddress: 0.0.0.0
