---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticache-install
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticache-install
rules:
- apiGroups: ["elasticache.services.k8s.aws"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["secretgen.carvel.dev", "secretgen.k14s.io"]
  resources: ["secrettemplates","passwords"]
  verbs:     ["*"]
- apiGroups: [""]
  resources: ["serviceaccounts","configmaps"]
  verbs:     ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs:     ["get", "list"]  
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles","rolebindings"]
  verbs:     ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elasticache-install
subjects:
- kind: ServiceAccount
  name: elasticache-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: elasticache-install
